include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/models/*.g.dart
    - lib/generated_*.dart

linter:
  rules:
    prefer_const_constructors: false
