name: natura
description: natura flutter app

publish_to: 'none'

version: 1.4.20+84

environment:
  sdk: ">=3.0.0 <4.0.0"

module:
  androidX: true

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  digit_to_word: ^1.2.1
  firebase_analytics: ^11.4.1
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  google_fonts: ^4.0.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_mobile_ads: ^5.3.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.3.1
  http: ^0.13.0
  in_app_purchase: ^3.2.0
  in_app_review: ^2.0.9
  json_annotation: ^4.9.0
  link_text: ^0.2.1
  numberpicker: ^2.1.2
  package_info_plus: ^8.0.0
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  share_plus: ^10.1.4
  shared_preferences: ^2.2.3
  speech_to_text: ^7.0.0
  #speech_to_text:
  #  path: /ara/devel/sandbox/speech_to_text/speech_to_text
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  video_player: ^2.8.6
  wakelock_plus: ^1.2.5

  collection: any
dev_dependencies:
  build_runner: ^2.4.10
  effective_dart: ^1.3.2
  flutter_launcher_icons: # using custom fork due to a bug: https://github.com/fluttercommunity/flutter_launcher_icons/pull/181
    git:
      url: https://github.com/SimonIT/flutter_launcher_icons
      ref: scaling
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_icons:
  image_path: 'assets/icons/icon.png'
  adaptive_icon_background: '#FFFFFFFF'
  adaptive_icon_foreground: 'assets/icons/icon-adaptive.png'
  adaptive_icon_foreground_scale_factor: 0.66
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: false

flutter:

  uses-material-design: true

  assets:
    - assets/icons/icon-adaptive.png
    - assets/images/no_image.png
    - assets/images/placeholder_banners/1.png
    - assets/images/placeholder_banners/2.png
    - assets/images/placeholder_banners/3.png
    - assets/images/placeholder_banners/4.png
    - assets/images/placeholder_banners/5.png
    - assets/images/video-frame.jpg
    - assets/sounds/speech_to_text_cancel.m4r
    - assets/sounds/speech_to_text_listening.m4r
    - assets/sounds/speech_to_text_stop.m4r
    - assets/video/flag_eagle.mp4
