name: Flutter analyze and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  flutter_version: '3.0.x'

jobs:
  test:
    name: Run flutter analyze and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
      
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --fatal-infos
      
      - name: Verify formatting
        run: ./scripts/format.sh

      - name: Run tests
        run: flutter test
